name: MADpy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - dotmap
  - dask
  - pyarrow
  - dill
  - jax
  - joblib
  - pypdf2
  - pip:
    - git+https://github.com/pyro-ppl/numpyro.git
    - --editable=. # install MADpy here