[tool.poetry]
name = "MADpy"
version = "0.1.0"
description = "Metagenomics Ancient Damage python: MADpy"
authors = ["Christian Michelsen <christianmichelsen@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
pip = "^20.3.3"
numpyro = "^0.4.1"
pandas = "^1.2.0"
dotmap = "^1.3.23"
matplotlib = "^3.3.3"
dask = {extras = ["distributed"], version = "^2020.12.0"}
fsspec = "^0.8.5"
dill = "^0.3.3"
PyPDF2 = "^1.26.0"
joblib = "^1.0.0"
pyarrow = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
flake8 = "^3.8.4"
ipykernel = "^5.4.3"
black = {version = "^20.8b1", allow-prereleases = true}
pylint = "^2.6.0"

[tool.poetry.scripts]
MADpy = "MADpy.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
