[tool.poetry]
name = "metadamage"
version = "0.1.8"
description = "Metagenomics Ancient Damage: metadamage"
authors = ["Christian Michelsen <christianmichelsen@gmail.com>"]
license = "MIT"
keywords = ['metadamage', 'metagenomics', 'ancient damage', 'DNA damage']
repository = "https://github.com/ChristianMichelsen/metadamage"
readme = "README.md"
include = ["metadamage/style.mplstyle", 'pyproject.toml']


[tool.poetry.dependencies]
python = "^3.8"
pip = "^20.3.3"
numpyro = "^0.4.1"
pandas = "^1.2.0"
dotmap = "^1.3.23"
matplotlib = "^3.3.3"
dask = {extras = ["distributed"], version = "^2020.12.0"}
fsspec = "^0.8.5"
dill = "^0.3.3"
PyPDF2 = "^1.26.0"
joblib = "^1.0.0"
pyarrow = "^2.0.0"
rich = "^9.8.1"
dotted-dict = "^1.1.3"
typer = {extras = ["all"], version = "^0.3.2"}
fire = "^0.3.1"
click-help-colors = "^0.9"
tqdm = "^4.56.0"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^4.6"
flake8 = "^3.8.4"
ipykernel = "^5.4.3"
black = {version = "^20.8b1", allow-prereleases = true}
pylint = "^2.6.0"
mypy = "^0.790"
twine = "^3.3.0"

[tool.poetry.scripts]
metadamage = "metadamage.cli:main_cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
